# Generated by Django 4.2.6 on 2023-10-17 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Fitfeed', '0002_alter_customers_date_created_alter_customers_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumeditems',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fitfeed.customers'),
        ),
    ]
