# Generated by Django 4.2.6 on 2023-10-19 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fitfeed', '0005_remove_fooditems_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditems',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
